pages/urls.py
from django.contrib import admin

from django.views.decorators.cache import cache_page

from django.urls import (
    path,
    re_path,
    include
)

from . import views

app_name = 'pages'

urlpatterns = [

    re_path(
        r'^$',
        views.HomeView.as_view(),
        name='home'),

    re_path(
        r'^contact/$',
        views.ContactCreateView.as_view(),
        name='contact'),

    re_path(
        r'^about/$',
        views.AboutView.as_view(),
        name='about'),

    re_path(
        r'^properties/$',
        views.PropertyListView.as_view(),
        name='properties'),

    re_path(
        r'^properties/page/(?P<page>[\d]+)/$',
        views.PropertyListView.as_view(),
        name='properties'
    ),

    re_path(
        r'^property/(?P<slug>[-\w]+)/$',
        views.PropertyDetailView.as_view(),
        name='property'),

    re_path(
        r'^property/tag/(?P<slug>[-\w]+)/page/(?P<page>[\d]+)/$',
        views.PropertyTagDetailView.as_view(),
        name='property_tag'),

    re_path(
        r'^property/category/(?P<slug>[-\w]+)/page/(?P<page>[\d]+)/$',
        views.ListCategoryProperties.as_view(),
        name='property_category'
    ),

    re_path(
        r'^footer/$',
        views.NewsletterPartialView.as_view(),
        name='footer'),

]

media/templates/partials/copy-right.html
<div class="copyright copyright--blue">
    <div class="container d-flex justify-content-center">
        <a href="https://sepehrakbarzadeh.ir"><p style="color: #FFFFFF" class="mb-0">SAGE team</p></a>
    </div>
</div>
<a class="scroll--dark" href="#" id="scroll" style="display: none"
><span></span
></a>

media/templates/partials/footer.html
{% load static %}

<footer class="footer footer--dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-6 mb-5">
                <a href="{% url 'pages:home' %}" class="footer__brand"
                ><img src="{{ site.svg.url }}" alt="{{ site.svg_alt_text }}"
                /></a>

                <p class="mb-4">
                    {{ site.footer_text }}
                </p>
                <ul class="list-inline footer__contact">
                    <li class="list-inline-item">
                        <p>
                            <i class="fas fa-phone-alt" aria-hidden="true"></i>
                            {{ site.phone_number }}
                        </p>
                    </li><br/>
                    <li class="list-inline-item">
                        <p>
                            <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                            {{ site.address }}
                        </p>
                    </li><br/>
                    <li class="list-inline-item">
                        <p>
                            <i class="fas fa-envelope" aria-hidden="true"></i>
                            {{ site.email }}
                        </p>
                    </li>

                </ul>
            </div>
            <div class="col-lg-4 col-md-6 mb-5">
                <div class="footer__news footer__news--dark">
                    <h3 class="title_1 title_1--dark">اشتراک در خبرنامه</h3>
                    <p class="mb-3">
                        کافیست برای اشتراک در خبرنامه با پر کردن فرم زیر ما را مطلع سازید تا از پیشنهاد‌ها جدید بی خبر نمانید.
                    </p>
                    <form method="post" action="{% url 'pages:footer' %}">
                        {% csrf_token %}

                        {{ form }}

{#                        <input#}
{#                                type="email"#}
{#                                id="subscribeEmail"#}
{#                                name="EMAIL"#}
{#                                placeholder="ایمیل خود را وارد کنید"#}
{#                        />#}
                        <input type="submit" value="اشتراک در خبرنامه"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</footer>

media/templates/partials/mobile-nav.html
<div id="mySidenav" class="sidenav d-block d-lg-none">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"
    >&times;</a
    >

    <div id="cssmenu">
        <span class="title">منو</span>
        <ul>
            <li>
                <a href="{% url 'pages:home' %}"><span>خانه</span></a>
            </li>
            <li class="active has-sub">
                <a href="#"
                ><span>دسته‌بندی‌ها</span>
                    <i class="fas fa-angle-down" aria-hidden="true"></i
                    ></a>

                <ul>

                    <li>
                        <a href="#"><span>Sub Product</span></a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><span>About</span></a>
            </li>
            <li class="last">
                <a href="#"><span>Contact</span></a>
            </li>
        </ul>
    </div>
</div>

media/templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar--dark sticky-top navbar-light">
    <div class="container-fluid">
        <button class="menu-toggler d-block d-lg-none" onclick="openNav()">
            <div class="menu-toggle-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <a class="navbar-brand" href="{% url 'pages:home' %}"
        ><img src="{{ site.svg.url }}" alt="{{ site.svg_alt_text }}"
        /></a>
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if view.page_name == 'خانه' %}active{% endif %}">
                    <a class="nav-link nav-link--dark" href="{% url 'pages:home' %}">خانه</a>
                </li>
                <li class="nav-item {% if view.page_name == 'درباره ما' %}active{% endif %}">
                    <a class="nav-link nav-link--dark" href="{% url 'pages:about' %}">درباره ما</a>
                </li>
                <li class="nav-item {% if view.page_name == 'تماس باما' %}active{% endif %}">
                    <a class="nav-link nav-link--dark" href="{% url 'pages:contact' %}">تماس باما</a>
                </li>
                <li class="nav-item {% if view.page_name == 'املاک' %}active{% endif %}">
                    <a class="nav-link nav-link--dark" href="{% url 'pages:properties' %}">املاک</a>
                </li>
                <li class="nav-item dropdown">
                    <a
                            class="nav-link dropdown-toggle nav-link--dark"
                            href="#"
                            id="navbarDropdown"
                            role="button"
                            aria-haspopup="true"
                            aria-expanded="false"
                    >
                        دسته‌بندی‌ها
                        <i
                                class="fas fa-angle-down dropdown-toggle__arrow dropdown-toggle__arrow--dark"
                        ></i>
                    </a>
                    <div class="dropdown-menu m-0" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

media/templates/partials/scripts.html
{% load static %}

    <script src="{% static 'assets/vendors/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/vendors/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendors/js/owl.carousel.min.js' %}"></script>
    <script
      src="https://kit.fontawesome.com/7a21f8c96b.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'assets/vendors/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendors/js/lightslider.js' %}"></script>
    <script src="{% static 'assets/gilda/gilda.js' %}"></script>

media/templates/partials/styles.html
{% load static %}

<link
      rel="stylesheet"
      href="{% static 'assets/vendors/fonts/font/iran-sans/css/fontiran.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/fonts/font_num/css/fontiran.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/fonts/vazir/vazir-font/css/main.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css"
      integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'assets/vendors/css/hover.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/css/owl.carousel.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/css/owl.theme.default.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/vendors/css/lightslider.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/gilda/gilda.css' %}" />

media/templates/partials/video-banner.html
{% load static %}

<div class="video-banner">
    <video poster="{% static 'assets/img/bg/video-poster2.png' %}" autoplay muted loop>
        <source src="{{ banner.video.url }}" type="video/mp4"/>
        Your browser does not support HTML5 video.
    </video>

    <div class="video-banner__content text-center">
        <h1 class="mb-2">{{ banner.title }}</h1>
        <p class="mb-0">{{ banner.summary }}</p>
    </div>
</div>