pages/urls.py
from django.contrib import admin

from django.views.decorators.cache import cache_page

from django.urls import (
    path,
    re_path,
    include
)

from . import views

app_name = 'pages'

urlpatterns = [

    re_path(
        r'^$',
        views.HomeView.as_view(),
        name='home'),

    re_path(
        r'^contact/$',
        views.ContactCreateView.as_view(),
        name='contact'),

    re_path(
        r'^about/$',
        views.AboutView.as_view(),
        name='about'),

    re_path(
        r'^properties/$',
        views.PropertyListView.as_view(),
        name='properties'),

    re_path(
        r'^properties/page/(?P<page>[\d]+)/$',
        views.PropertyListView.as_view(),
        name='properties'
    ),

    re_path(
        r'^property/(?P<slug>[-\w]+)/$',
        views.PropertyDetailView.as_view(),
        name='property'),

    re_path(
        r'^property/tag/(?P<slug>[-\w]+)/page/(?P<page>[\d]+)/$',
        views.PropertyTagDetailView.as_view(),
        name='property_tag'),

    re_path(
        r'^property/category/(?P<slug>[-\w]+)/page/(?P<page>[\d]+)/$',
        views.ListCategoryProperties.as_view(),
        name='property_category'
    ),

    re_path(
        r'^footer/$',
        views.NewsletterPartialView.as_view(),
        name='footer'),

]

property/models.py
import secrets

from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from django.urls import reverse

from django.core.validators import (
    FileExtensionValidator,
    RegexValidator, MaxLengthValidator, MinLengthValidator
)

from painless.utils.upload.path import date_directory_path

from painless.utils.models.common import (
    TimeStampModelMixin,
    ImageModelMixin,
    TitleSlugLinkModelMixin,
    VideoModelMixin
)


class Property(TitleSlugLinkModelMixin, ImageModelMixin, TimeStampModelMixin):
    STATUS = (
        ('r', _('اجاره')),
        ('b', _('فروش'))
    )

    KIND = (
        ('a', _('آپارتمان')),
        ('h', _('خانه')),
        ('g', _('زمین'))
    )

    poster_picture = models.ImageField(
        _("Poster Picture"),
        upload_to=date_directory_path,
        height_field='poster_height_field',
        width_field='poster_width_field',
        max_length=110,
        blank=True,
        null=True,
        validators=[FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'jpg', 'jpeg', 'png'])]
    )

    poster_picture_alternate_text = models.CharField(
        _("Poster Picture Alternate Text"),
        max_length=110,
        validators=[
            MaxLengthValidator(150),
            MinLengthValidator(3)
        ],
        blank=True,
        null=True
    )
    poster_width_field = models.PositiveSmallIntegerField(_("Width Field"), blank=True, null=True, editable=False)
    poster_height_field = models.PositiveSmallIntegerField(_("Height Field"), blank=True, null=True, editable=False)

    video = models.FileField(
        _("Video"),
        upload_to=date_directory_path,
        max_length=110,
        validators=[
            FileExtensionValidator(allowed_extensions=['mp4', ])
        ],
        blank=True,
        null=True
    )

    video_alternate_text = models.CharField(
        _("Video Alternate Text"),
        max_length=110,
        validators=[
            MaxLengthValidator(150),
            MinLengthValidator(3)
        ],
        blank=True,
        null=True
    )

    sku = models.CharField(_("SKU"), editable=False, max_length=7)

    price = models.CharField(
        _("Price"),
        max_length=16,
        validators=[
            RegexValidator(r'\d+', message=_('price must be digit.')),
        ],
    )
    is_featured = models.BooleanField(_("Is Featured"), default=False)
    is_popular = models.BooleanField(_("Is Popular"), default=False)

    status = models.CharField(_("Status"), choices=STATUS, max_length=1)
    kind = models.CharField(_("Kind"), choices=KIND, max_length=1)
    area = models.CharField(
        _("Area"),
        max_length=12,
        validators=[RegexValidator(r'\d+x\d+',
                                   message=_("Please enter area in this format `(100x200)`. TIP: (width, height) "))]
    )

    description = models.TextField(_("Description"))

    category = models.ForeignKey('Category', related_name='properties', on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        self.sku = secrets.token_hex(3).upper()
        self.slug = slugify(self.title, allow_unicode=True)
        super(Property, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pages:property', kwargs={'slug': self.slug})

    def get_price(self):
        return "{:,.0f}".format(float(self.price))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Property')
        verbose_name_plural = _('Properties')


class Category(TitleSlugLinkModelMixin, TimeStampModelMixin):
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pages:property_category', kwargs={'slug': self.slug, 'page': 1})

    def __str__(self):
        return self.title


class Tag(TitleSlugLinkModelMixin, TimeStampModelMixin):
    item = models.ManyToManyField("Property", db_column='property', related_name='tag', verbose_name=_("Tag Property"))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Tag, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pages:property_tag', kwargs={'slug': self.slug, 'page': 1})

    def __str__(self):
        return self.title


class Feature(TitleSlugLinkModelMixin, TimeStampModelMixin):
    item = models.ForeignKey(
        Property,
        db_column='property',
        verbose_name=_("Property"),
        related_name='features',
        on_delete=models.CASCADE
    )

    icon = models.ForeignKey(
        'Icon',
        db_column='icon',
        verbose_name=_("Icon"),
        related_name='features',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Feature, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('property_feature', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Gallery(TimeStampModelMixin, ImageModelMixin):
    item = models.ForeignKey(Property, db_column='property', verbose_name=_("Feature"), related_name='pictures',
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.picture_alternate_text

    def get_absolute_url(self):
        return reverse('property_gallery', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = _('Gallery')
        verbose_name_plural = _('Galleries')


class Amenities(TimeStampModelMixin):
    key = models.CharField(_("Key"), max_length=150)
    value = models.BooleanField(_("Value"))
    item = models.ForeignKey(Property, db_column='property', verbose_name=_("Amenities"), related_name='ameneties',
                             on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('property_aminity', kwargs={'slug': self.slug})

    def __str__(self):
        return self.key


class Detail(TimeStampModelMixin):
    key = models.CharField(_("Key"), max_length=150)
    value = models.CharField(_("Key"), max_length=150)
    item = models.ForeignKey(Property, db_column='property', verbose_name=_("Detail"), related_name='details',
                             on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('property_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.key


class Icon(models.Model):
    name = models.CharField(
        max_length=30,
        verbose_name=_("Name"),
    )

    code = models.CharField(
        _("Code"),
        max_length=30,
    )

    def __str__(self):
        return self.name

property/forms.py
from django import forms

from .models import (
    Amenities,
    Property,
    Category,
    Tag,
    Feature,
    Gallery,
    Detail
)

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['title', 'price', 'is_featured', 'status', 'kind', 'area', 'description', 'floorplan', 'alternate_text_floorplan', 'width_field_floorplan', 'height_field_floorplan', 'category',]

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title',]

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'item']

class FeatureForm(forms.ModelForm):
    class Meta:
        model = Feature
        fields = ['title', 'item']

class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['item', 'picture', 'alternate_text',]

class AmenityForm(forms.ModelForm):
    class Meta:
        model = Amenities
        fields = ['key', 'value', 'item']

class Detail(forms.ModelForm):
    class Meta:
        model = Detail
        fields = ['key', 'value', 'item']

property/views.py
from django.shortcuts import render

# Create your views here.

media/templates/pages/about-us.html
{% extends 'shared/_base.html' %}
{% load static %}

{% block body %}

    <div class="banner">
        <div class="banner__content">
            <h4 class="banner__title text-center">درباره ما</h4>
            <ul class="banner__breadcrumb list-inline text-center">
                <li class="list-inline-item">
                    <p><a href="{% url 'pages:home' %}">خانه</a></p>
                </li>
                <li class="divider list-inline-item">/</li>
                <li class="list-inline-item"><p>درباره ما</p></li>
            </ul>
        </div>
    </div>
    <div class="find-houses section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-12">
                    <h2 class="text-left mb-4 title_2">
                        درباره <span>{{ site.site_name }}</span>
                    </h2>
                    <h4 class="mb-4">
                        {{ site.about_us_title }}
                    </h4>
                    <p class="mb-4">
                        {{ site.about_us }}
                    </p>
                </div>
                <div class="col-lg-6 col-12">
                    <img
                            class="img-fluid"
                            src="{{ site.about_us_pic.url }}"
                            alt="{{ site.about_us_alternate_text }}"
                    />
                </div>
            </div>
        </div>
    </div>
    <div class="our-services section_padding">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-title">
                        <h3>کلارستان</h3>
                        <h2>خدمات</h2>
                    </div>
                </div>
                {% for service in services %}
                    <div class="col-md-3">
                        <div class="service">
                            <img src="{{ service.picture.url }}" alt="{{ service.picture_alternate_text }}"/>
                            <h3>{{ service.title }}</h3>
                            <p>
                                {{ service.description }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

media/templates/pages/index.html
{% extends 'shared/_base.html' %}
{% load static %}

{% block body %}

    {% include 'partials/video-banner.html' %}

    {% if properties %}

        <div class="recently-properties section_padding">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title section-title--orange">
                            <h3>کلارستان</h3>
                            <h2>برترین های برگزیده</h2>
                        </div>
                    </div>

                    {% for property in properties %}

                        <div class="col-lg-4 col-md-6">
                            <div class="project">
                                <div class="project__header">
                                    <img src="{{ property.picture.url }}" alt="{{ property.picture_alternate_text }}"/>
                                    <a href="#" class="badge badge--sale badge--top-right"
                                    >{{ property.get_status_display }}</a
                                    >

                                    {% if property.is_featured %}

                                        <a href="#" class="badge badge--feature badge--top-left"
                                        >ویژه</a
                                        >

                                    {% endif %}

                                    <a href="#" class="badge badge--family badge--bottom-left">
                                        {{ property.get_kind_display }}
                                    </a>
                                    <div class="project__overlay">
                                        <a href="{% url 'pages:property' property.slug %}">
                                            <h4>
                                                {{ property.title }}
                                                <br/>
                                                <span>نمایش جزئیات بیشتر</span>
                                            </h4>
                                        </a>
                                    </div>
                                </div>

                                <div class="project__content">
                                    <h3 class="project__content__title">
                                        <a href="{{ property.get_absolute_url }}">
                                            {{ property.title }}
                                        </a>
                                    </h3>
                                    <p class="project__content__address">
                                        <a href="{{ property.category.get_absolute_url }}">
                                            <i class="fa fa-list-alt"></i>
                                            <span>
                                                {{ property.category }}
                                            </span>
                                        </a>
                                    </p>

                                    <ul class="project__content__details">
                                        {% for feature in property.features.all %}
                                            <li>
                                                <i class="{{ feature.icon.code }}" aria-hidden="true"></i>
                                                <span>{{ feature.title }}</span>
                                            </li>
                                        {% endfor %}
                                    </ul>

                                    <div class="project__content__properties">
                                        <h3>
                                            <a href="{{ property.get_absolute_url }}">{{ property.get_price }}</a>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                    <div class="col-12 mb-4"></div>
                    <div class="col-12 text-center">
                        <a href="{% url 'pages:properties' %}" class="link-primary"
                        >نمایش همه <i class="fas fa-arrow-circle-right"></i
                        ></a>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

    <div class="welcome-to-find-houses section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="mb-2">خوش آمدید به <span>{{ site.site_name }}</span></h2>
                    <h4 class="mb-4">{{ site.welcome_title }}</h4>
                    <p class="mb-5">
                        {{ site.welcome_summary }}
                    </p>
                    <ul>
                        {% for service in services %}
                            <li>
                                <img src="{{ service.picture.url }}" alt="{{ service.picture_alternate_text }}"/>
                                <div class="content">
                                    <h6>{{ service.title }}</h6>
                                    <p>
                                        {{ service.description }}
                                    </p>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="col-lg-6">
                    <img
                            class="img-fluid"
                            src="{{ site.picture.url }}"
                            alt="{{ site.picture_alternate_text }}"
                    />
                </div>
            </div>
        </div>
    </div>


    {% if popularـproperties %}

        <div class="popular-places section_padding">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title section-title--orange">
                            <h3>کلارستان</h3>
                            <h2>محبوب ترین‌ها</h2>
                        </div>
                    </div>

                    {% for popular in popularـproperties %}

                        {% if forloop.first or forloop.counter == 4 %}

                            <div class="col-lg-4 col-md-6">
                                <a class="hover-image" href="{% url 'pages:property' popular.slug %}">

                                    <div class="hover-image__content">

                                        {% if popular.is_featured %}
                                            <span class="featured">Featured</span>
                                        {% endif %}

                                        <img src="{{ popular.picture.url }}"
                                             alt="{{ popular.picture_alternate_text }}"/>
                                        <h4>
                                            {{ popular.title }}
                                            <br/>
                                            <span>{{ popular.get_status_display }}</span>
                                        </h4>
                                    </div>

                                </a>
                            </div>

                        {% else %}

                            <div class="col-lg-8 col-md-6">
                                <a class="hover-image" href="{% url 'pages:property' popular.slug %}">

                                    <div class="hover-image__content">

                                        {% if popular.is_featured %}
                                            <span class="featured">ویژه</span>
                                        {% endif %}

                                        <img src="{{ popular.picture.url }}" alt="{{ popular.picture_alternate_text }}"/>
                                        <h4>
                                            {{ popular.title }}
                                            <br/>
                                            <span>{{ popular.get_status_display }}</span>
                                        </h4>
                                    </div>

                                </a>
                            </div>

                        {% endif %}

                    {% endfor %}

                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

media/templates/pages/property-category.html
{% extends 'shared/_base.html' %}
{% load static %}

{% block title %}
    {{ category.title }} | {{ site.site_name }}
{% endblock %}

{% block body %}

    <div class="banner">
        <div class="banner__content">
            <h4 class="banner__title text-center">{{ category.title }}</h4>
            <ul class="banner__breadcrumb list-inline text-center">
                <li class="list-inline-item">
                    <p><a href="{% url 'pages:home' %}">خانه</a></p>
                </li>
                <li class="divider list-inline-item">/</li>
                <li class="list-inline-item"><p>{{ category.title }}</p></li>
            </ul>
        </div>
    </div>

    <div class="grid section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-12 pb-5">

                            <h4 class="grid__title mb-2">{{ category.title }}</h4>

                        </div>

                        {% for property in properties %}

                            <div class="col-md-6">
                                <div class="project">
                                    <div class="project__header">
                                        <img src="{{ property.picture.url }}"
                                             alt="{{ property.picture_alternate_text }}"/>
                                        <a href="#" class="badge badge--sale badge--top-right"
                                        >{{ property.get_status_display }}</a
                                        >

                                        {% if property.is_featured %}

                                            <a href="#" class="badge badge--feature badge--top-left"
                                            >ویژه</a
                                            >

                                        {% endif %}

                                        <a href="{{ property.get_absolute_url }}" class="badge badge--family badge--bottom-left">
                                            {{ property.get_kind_display }}
                                        </a>
                                        <div class="project__overlay">
                                            <a href="{{ property.get_absolute_url }}">
                                                <h4>
                                                    {{ property.title }}
                                                    <br/>
                                                    <span>نمایش جرئيات بیشتر</span>
                                                </h4>
                                            </a>
                                        </div>
                                    </div>

                                    <div class="project__content">
                                        <h3 class="project__content__title">
                                            <a href="{{ property.get_absolute_url }}">
                                                {{ property.title }}
                                            </a>
                                        </h3>
                                        <p class="project__content__address">
                                            <a href="{{ property.category.get_absolute_url }}">
                                                <i class="fa fa-list-alt"></i>
                                                <span>
                                                {{ property.category }}
                                            </span>
                                            </a>
                                        </p>

                                        <ul class="project__content__details">
                                            {% for feature in property.features.all %}
                                                <li>
                                                    <i class="{{ feature.icon.code }}" aria-hidden="true"></i>
                                                    <span>{{ feature.title }}</span>
                                                </li>
                                            {% endfor %}
                                        </ul>

                                        <div class="project__content__properties">
                                            <h3>
                                                <a href="{{ property.get_absolute_url }}">{{ property.get_price }}</a>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}

                        {% if properties.has_other_pages %}

                            <div class="col-12 mt-3">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if properties.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="{% url 'pages:property_category' category.slug properties.previous_page_number %}">
                                                    صفحه قبل
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link"
                                                   href="#">
                                                    صفحه قبل
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for i in properties.paginator.page_range %}

                                            {% if properties.number == i %}
                                                <li class="page-item active">
                                                    <a class="page-link"
                                                       href="{% url 'pages:property_category' category.slug i %}">{{ i }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link"
                                                       href="{% url 'pages:property_category' category.slug i %}">{{ i }}</a>
                                                </li>
                                            {% endif %}

                                        {% endfor %}
                                        {% if properties.has_next %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="{% url 'pages:property_category' category.slug properties.next_page_number %}">
                                                    صفحه بعد
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link"
                                                   href="">
                                                    صفحه بعد
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>

                        {% endif %}

                    </div>
                </div>

                <div class="col-lg-3 main-searchbar">
                    <h3 class="title_1 title_1--search mt-5">املاک اخیر</h3>
                    <div class="d-flex flex-wrap">
                        {% for property in recent_properties %}
                            <div class="recent-house">
                                <img src="{{ property.picture.url }}" alt="{{ property.picture_alternate_text }}"/>
                                <div class="info-img">
                                    <a href="{{ property.get_absolute_url }}"><h6>{{ property.title }}</h6></a>
                                    <p>{{ property.get_price }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <h3 class="title_1 title_1--search mt-5">برچسب‌های اخیر</h3>
                    <div class="tags">
                        {% for recent_tag in recent_tags %}
                            <a href="{{ recent_tag.get_absolute_url }}">{{ recent_tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}